### ISSUE TITLE
Renderer doesn't "unregister" on close

### ISSUE THREAD

**Issue by brendann993** [kettek/electron-app-settings#2]
When a renderer closes it doesn't unregister for events, this causes a "Object is distroyed" error in the main process if another renderer then tries to get or set settings.

I have worked around this by setting listeners as array  and then creating a remove event. e.g
Main.js
` let listeners = [];
  // ---- Register any listeners that request
  ipcMain.on('configurator-add-listener', (event) => {
	  let listener = event.sender
    	listeners.push(listener)
		// -- Send our settings over to the listener
		listener.send('configurator-master-set', {key: main_settings._storage});
  });
  // ---- Remove any listeners that request
  ipcMain.on('configurator-remove-listener', (event) => {
	let listener = event.sender
	listeners = listeners.filter(item => item !== listener)
  });
// -- Set our *set master events to listeners
	main_settings.on('set', (arg) => {
		listeners.forEach((listener)=>{
			listener.send('configurator-master-set', arg);
		})
	});
	main_settings.on('unset', (arg) => {
		listeners.forEach((listener)=>{
			listener.send('configurator-master-unset', arg);
		})
	});
`

and then in Renderer,js
`  window.addEventListener('beforeunload', ()=>{
	ipcRenderer.send('configurator-remove-listener');
	return
  })`

**Comment by brendann993** [comment]
#3  Pull request for added ability to unregister

**Comment by kettek** [comment]
Accepted and closed by 9f3b003.
